function dLossdX = convolveBackwardData2DCore( ...
    imageSize, W, dLossdZ, ...
    padTop, padLeft, ...
    padBottom, padRight, ...
    strideHeight, strideWidth)
% convolveBackwardData2DCore   Backpropagate through a
% convolutional layer to get the derivative with respect to the input.

% Copyright 2017 The MathWorks, Inc.

backwardFilterConvolution = false;
dLossdX = builtin('_batchconvBackward', dLossdZ, W, ...
    [padTop padLeft padBottom padRight], [strideHeight strideWidth],...
    imageSize, backwardFilterConvolution);

end

