classdef AveragePooling2DHostStrategy < nnet.internal.cnn.layer.util.ExecutionStrategy
    % AveragePooling2DHostStrategy   Execution strategy for running the average pooling on the host
    
    %   Copyright 2016-2017 The MathWorks, Inc.
    
    methods
        function [Z, memory] = forward(~, X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride)
            Z = nnet.internal.cnnhost.poolingAverageForward2D(X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride);
            memory = [];
        end
        
        function [dX,dW] = backward( ~, ...
                Z, dZ, X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                strideHeight, strideWidth)
            dX = nnet.internal.cnnhost.poolingAverageBackward2D( ...
                Z, dZ, X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                strideHeight, strideWidth, ...
                true);
            dW = [];
        end
        
    end
end