classdef MaxPooling2DGPUStrategy < nnet.internal.cnn.layer.util.ExecutionStrategy
    % MaxPooling2DGPUStrategy   Execution strategy for running the max pooling on the GPU
    
    %   Copyright 2016-2017 The MathWorks, Inc.
    
    methods
        function [Z, memory] = forward(~, X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride)
            Z = nnet.internal.cnngpu.poolingMaxForward2D(X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride);
            memory = [];
        end
        
        function [dX,dW] = backward(~, Z, dZ, X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride)
            dX = nnet.internal.cnngpu.poolingMaxBackward2D(...
                Z, dZ, X, ...
                poolHeight, poolWidth, ...
                topPad, leftPad, ...
                bottomPad, rightPad, ...
                verticalStride, horizontalStride);
            dW = [];
        end
    end
end